---
Name: fromholdio-grouploginredirect
---

SilverStripe\Security\Group:
  extensions:
    - Fromholdio\GroupLoginRedirect\Extensions\LoginGroupExtension

SilverStripe\Core\Injector\Injector:
  SilverStripe\Security\MemberAuthenticator\LoginHandler:
    class: Fromholdio\GroupLoginRedirect\Security\GroupLoginHandler
