---
Name: fromholdio-grouploginredirect
---

SilverStripe\Security\Group:
  extensions:
    - Fromholdio\Affinity\AwardSubmission\Extensions\LoginGroupExtension

SilverStripe\Core\Injector\Injector:
  SilverStripe\Security\MemberAuthenticator\LoginHandler:
    class: Fromholdio\Affinity\AwardSubmission\Security\GroupLoginHandler
